### ISSUE TITLE
Website seems broken with the Jekyll 3.0 update

### ISSUE THREAD

**Issue by karthikraman** [psolymos/psolymos.github.io#1]
Please check https://github.com/t413/SinglePaged/pull/37/files - the permalink edit alone fixed my site. Your site is wonderful BTW, and the inspiration for mine!

**Comment by psolymos** [comment]
Thanks @karthikraman for the PR and compliments. I have opted to revamp my site (see [peter.solymos.org](peter.solymos.org)) instead of fixing the single paged theme. Although I really liked the theme, there are several reasons for the change, and I list some of those here FYI:
- Single paged theme made it hard to see in Google analytics who is looking what on the site, because seemingly everyone looked at index.html.
- After a while, I wanted real blog and subpages, and I felt more comfortable tweaking bootstrap/bootswatch based themes. 
- I also had a web-update repo in the works, so transitioning was really easy (although migrating content and fine tuning took 3 days).

**Comment by karthikraman** [comment]
The new site looks awesome too!

**Comment by psolymos** [comment]
Thanks!
